version: '3'

services:
  stackstorm:
    container_name: stackstorm-server
    image: stackstorm/stackstorm:${ST2_IMAGE_TAG:-latest}
    env_file:
      - conf/stackstorm.env
      - conf/mongo.env
      - conf/rabbitmq.env
      - conf/postgres.env
      - conf/redis.env
    depends_on:
      - mongo
      - postgres
      - rabbitmq
      - redis
    networks:
      - public
      - private
    volumes:
      - stackstorm-packs-volume:/opt/stackstorm/packs
      - stackstorm-virtualenvs-volume:/opt/stackstorm/virtualenvs
      - stackstorm-configs-volume:/opt/stackstorm/configs
      - stackstorm-log-volume:/var/log
      - /opt/sw-docker/stackstorm/packs.dev:/opt/stackstorm/packs.dev
      - /opt/sw-docker/stackstorm/runtime/entrypoint.d:/st2-docker/entrypoint.d
      - /opt/sw-docker/stackstorm/runtime/st2.d:/st2-docker/st2.d
      - /opt/sw-docker/stackstorm/conf/stackstorm.env:/st2-docker/env
    dns_search: .
    environment:
      - VIRTUAL_HOST=${ST2_URL}
      - VIRTUAL_PROTO=https
      - VIRTUAL_PORT=443
      - LETSENCRYPT_HOST=${ST2_URL}
      - LETSENCRYPT_EMAIL=${ST2_ADMIN_EMAIL}

### External Services

  mongo:
    container_name: stackstorm-mongo
    image: mongo:3.4
    env_file:
      - conf/mongo.env
    networks:
      - private
    volumes:
      - mongo-volume:/data/db
      - mongo-configdb-volume:/data/configdb
    dns_search: .

  rabbitmq:
    container_name: stackstorm-rabbitmq
    image: rabbitmq:3.6-management
    env_file:
      - conf/rabbitmq.env
    networks:
      - private
    volumes:
      - rabbitmq-volume:/var/lib/rabbitmq
    dns_search: .

  postgres:
    container_name: stackstorm-postgres
    image: postgres:9.6
    env_file:
      - conf/postgres.env
    networks:
      - private
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    dns_search: .

  redis:
    container_name: stackstorm-redis
    image: redis:4.0
    env_file:
      - conf/redis.env
    networks:
      - private
    volumes:
      - redis-volume:/data
    dns_search: .
    command: [
      "bash", "-c",
      '
       docker-entrypoint.sh
       --requirepass "$$REDIS_PASSWORD"
      '
    ]

volumes:
  mongo-volume:
  mongo-configdb-volume:
  postgres-volume:
  rabbitmq-volume:
  redis-volume:
  stackstorm-packs-volume:
  stackstorm-virtualenvs-volume:
  stackstorm-configs-volume:
  stackstorm-log-volume:

networks:
  public:
    external:
      name: nginx-proxy
  private:
    driver: bridge
